#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/mysql-connector-java-8.0.27.jar:$APPDIR/lib/Soluci__inform_tica.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/itext.jar:$APPDIR/lib/pdf.jar:$APPDIR/lib/BezierSQLib.jar:$APPDIR/lib/mysql-connector-java-3.1.14-bin.jar:$APPDIR/lib/postgresql-9.2-1002.jdbc3.jar:$APPDIR/lib/sqlite-jdbc-3.7.2.jar" Soluci__inform_tica "$@"
